name: good_luck_comes
description: 检测成绩什么时候公布
version: 1.0.0
repository: https://github.com/share121/good-luck-comes

environment:
  sdk: ^3.4.1

dependencies:
  dio: ^5.5.0
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.4
  open_url: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
